name: "Snapshotter"
description: "Generate a snapshot version based on timestamp and commit hash"
author: "rohan23chhabra@gmail.com"

inputs:
  BASE_VERSION:
    description: "The base semantic version. For example, v1.2.3"
    required: true
    default: "v0.0.0"
  GITHUB_TOKEN:
    description: "The secret access token used to authenticate to GitHub"
    required: true
  GITHUB_USERNAME:
    description: "The username used to login to GitHub"
    required: true
  GITHUB_REPOSITORY:
    description: "The repository for which tag is to be generated for the latest commit"
    required: true

outputs:
  SNAPSHOT_VERSION:
    description: "The generated snapshot version"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.BASE_VERSION }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GITHUB_USERNAME }}
    - ${{ inputs.GITHUB_REPOSITORY }}

branding:
  icon: camera
  color: orange
